# Databricks notebook source
# MAGIC %run ../../../common/properties

# COMMAND ----------

dbutils.widgets.dropdown(
    name = 'table_operation',
    defaultValue = 'CREATE TABLE IF NOT EXISTS', 
    choices = [
        'CREATE TABLE IF NOT EXISTS',
        'CREATE OR REPLACE'
    ],
    label = '1- Table Operation'
)

table_operation = dbutils.widgets.get('table_operation')

# COMMAND ----------

table_name = 'acdoca'

# COMMAND ----------

spark,sql(f'''
    ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    SET TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'enabled');
''')

# COMMAND ----------

spark.sql(f'''
    -- CREATE TABLE IF NOT EXISTS
    {table_operation} {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    (
        RCLNT string,
        RLDNR string,
        RBUKRS string,
        GJAHR string,
        BELNR string,
        DOCLN string,
        RYEAR string,
        DOCNR_LD string,
        RRCTY string,
        RMVCT string,
        VORGN string,
        VRGNG string,
        BTTYPE string,
        AWTYP string,
        AWSYS string,
        AWORG string,
        AWREF string,
        AWITEM string,
        AWITGRP string,
        SUBTA string,
        XREVERSING string,
        XREVERSED string,
        XTRUEREV string,
        AWTYP_REV string,
        AWORG_REV string,
        AWREF_REV string,
        SUBTA_REV string,
        XSETTLING string,
        XSETTLED string,
        PREC_AWTYP string,
        PREC_AWSYS string,
        PREC_AWORG string,
        PREC_AWREF string,
        PREC_AWITEM string,
        PREC_SUBTA string,
        PREC_AWMULT binary,
        XSECONDARY string,
        RTCUR string,
        RWCUR string,
        RHCUR string,
        RKCUR string,
        ROCUR string,
        RVCUR string,
        RBCUR string,
        RCCUR string,
        RDCUR string,
        RECUR string,
        RFCUR string,
        RGCUR string,
        RCO_OCUR string,
        RUNIT string,
        RVUNIT string,
        RRUNIT string,
        RIUNIT string,
        QUNIT1 string,
        QUNIT2 string,
        QUNIT3 string,
        CO_MEINH string,
        RACCT string,
        RCNTR string,
        PRCTR string,
        RFAREA string,
        RBUSA string,
        KOKRS string,
        SEGMENT string,
        SCNTR string,
        PPRCTR string,
        SFAREA string,
        SBUSA string,
        RASSC string,
        PSEGMENT string,
        TSL decimal(38,18),
        WSL decimal(38,18),
        WSL2 decimal(38,18),
        WSL3 decimal(38,18),
        HSL decimal(38,18),
        KSL decimal(38,18),
        OSL decimal(38,18),
        VSL decimal(38,18),
        BSL decimal(38,18),
        CSL decimal(38,18),
        DSL decimal(38,18),
        ESL decimal(38,18),
        FSL decimal(38,18),
        GSL decimal(38,18),
        KFSL decimal(38,18),
        KFSL2 decimal(38,18),
        KFSL3 decimal(38,18),
        PSL decimal(38,18),
        PSL2 decimal(38,18),
        PSL3 decimal(38,18),
        PFSL decimal(38,18),
        PFSL2 decimal(38,18),
        PFSL3 decimal(38,18),
        CO_OSL decimal(38,18),
        HSALK3 decimal(38,18),
        KSALK3 decimal(38,18),
        OSALK3 decimal(38,18),
        VSALK3 decimal(38,18),
        HSALKV decimal(38,18),
        KSALKV decimal(38,18),
        OSALKV decimal(38,18),
        VSALKV decimal(38,18),
        HPVPRS decimal(38,18),
        KPVPRS decimal(38,18),
        OPVPRS decimal(38,18),
        VPVPRS decimal(38,18),
        HSTPRS decimal(38,18),
        KSTPRS decimal(38,18),
        OSTPRS decimal(38,18),
        VSTPRS decimal(38,18),
        HSLALT decimal(38,18),
        KSLALT decimal(38,18),
        OSLALT decimal(38,18),
        VSLALT decimal(38,18),
        HSLEXT decimal(38,18),
        KSLEXT decimal(38,18),
        OSLEXT decimal(38,18),
        VSLEXT decimal(38,18),
        HVKWRT decimal(38,18),
        HVKSAL decimal(38,18),
        MSL decimal(38,18),
        MFSL decimal(38,18),
        VMSL decimal(38,18),
        VMFSL decimal(38,18),
        RMSL decimal(38,18),
        QUANT1 decimal(38,18),
        QUANT2 decimal(38,18),
        QUANT3 decimal(38,18),
        CO_MEGBTR decimal(38,18),
        CO_MEFBTR decimal(38,18),
        LBKUM decimal(38,18),
        DRCRK string,
        POPER string,
        PERIV string,
        FISCYEARPER string,
        BUDAT string,
        BLDAT string,
        BLART string,
        BUZEI string,
        ZUONR string,
        BSCHL string,
        BSTAT string,
        LINETYPE string,
        KTOSL string,
        SLALITTYPE string,
        XSPLITMOD string,
        USNAM string,
        TIMESTAMP decimal(38,18),
        EPRCTR string,
        RHOART string,
        GLACCOUNT_TYPE string,
        KTOPL string,
        LOKKT string,
        KTOP2 string,
        REBZG string,
        REBZJ string,
        REBZZ string,
        REBZT string,
        RBEST string,
        EBELN string,
        EBELP string,
        ZEKKN string,
        SGTXT string,
        KDAUF string,
        KDPOS string,
        MATNR string,
        WERKS string,
        LIFNR string,
        KUNNR string,
        FBUDA string,
        KOART string,
        UMSKZ string,
        MWSKZ string,
        HBKID string,
        HKTID string,
        XOPVW string,
        AUGDT string,
        AUGBL string,
        AUGGJ string,
        AFABE string,
        ANLN1 string,
        ANLN2 string,
        BZDAT string,
        ANBWA string,
        MOVCAT string,
        DEPR_PERIOD string,
        ANLGR string,
        ANLGR2 string,
        SETTLEMENT_RULE string,
        ANLKL string,
        KTOGR string,
        PANL1 string,
        PANL2 string,
        UBZDT_PN string,
        XVABG_PN string,
        PROZS_PN decimal(38,18),
        XMANPROPVAL_PN string,
        KALNR string,
        VPRSV string,
        MLAST string,
        KZBWS string,
        XOBEW string,
        SOBKZ string,
        VTSTAMP decimal(38,18),
        MAT_KDAUF string,
        MAT_KDPOS string,
        MAT_PSPNR string,
        MAT_PS_POSID string,
        MAT_LIFNR string,
        BWTAR string,
        BWKEY string,
        HPEINH decimal(38,18),
        KPEINH decimal(38,18),
        OPEINH decimal(38,18),
        VPEINH decimal(38,18),
        MLPTYP string,
        MLCATEG string,
        QSBVALT string,
        QSPROCESS string,
        PERART string,
        MLPOSNR string,
        BUKRS_SENDER string,
        RACCT_SENDER string,
        ACCAS_SENDER string,
        ACCASTY_SENDER string,
        OBJNR string,
        HRKFT string,
        HKGRP string,
        PAROB1 string,
        PAROBSRC string,
        USPOB string,
        CO_BELKZ string,
        CO_BEKNZ string,
        BELTP string,
        MUVFLG string,
        GKONT string,
        GKOAR string,
        ERLKZ string,
        PERNR string,
        PAOBJNR string,
        XPAOBJNR_CO_REL string,
        SCOPE string,
        LOGSYSO string,
        PBUKRS string,
        PSCOPE string,
        LOGSYSP string,
        BWSTRAT string,
        OBJNR_HK string,
        AUFNR_ORG string,
        UKOSTL string,
        ULSTAR string,
        UPRZNR string,
        UPRCTR string,
        ACCAS string,
        ACCASTY string,
        LSTAR string,
        AUFNR string,
        AUTYP string,
        PS_PSP_PNR string,
        PS_POSID string,
        PS_PSPID string,
        NPLNR string,
        NPLNR_VORGN string,
        PRZNR string,
        KSTRG string,
        BEMOT string,
        RSRCE string,
        QMNUM string,
        ERKRS string,
        PACCAS string,
        PACCASTY string,
        PLSTAR string,
        PAUFNR string,
        PAUTYP string,
        PPS_POSID string,
        PPS_PSPID string,
        PKDAUF string,
        PKDPOS string,
        PPAOBJNR string,
        PNPLNR string,
        PNPLNR_VORGN string,
        PPRZNR string,
        PKSTRG string,
        CO_ACCASTY_N1 string,
        CO_ACCASTY_N2 string,
        CO_ACCASTY_N3 string,
        CO_ZLENR string,
        CO_BELNR string,
        CO_BUZEI string,
        CO_BUZEI1 string,
        CO_BUZEI2 string,
        CO_BUZEI5 string,
        CO_BUZEI6 string,
        CO_BUZEI7 string,
        CO_REFBZ string,
        CO_REFBZ1 string,
        CO_REFBZ2 string,
        CO_REFBZ5 string,
        CO_REFBZ6 string,
        CO_REFBZ7 string,
        WORK_ITEM_ID string,
        ARBID string,
        VORNR string,
        AUFPS string,
        UVORN string,
        EQUNR string,
        TPLNR string,
        ISTRU string,
        ILART string,
        PLKNZ string,
        ARTPR string,
        PRIOK string,
        MAUFNR string,
        MATKL_MM string,
        PLANNED_PARTS_WORK string,
        FKART string,
        VKORG string,
        VTWEG string,
        SPART string,
        MATNR_COPA string,
        MATKL string,
        KDGRP string,
        LAND1 string,
        BRSCH string,
        BZIRK string,
        KUNRE string,
        KUNWE string,
        KONZS string,
        ACDOC_COPA_EEW_DUMMY_PA string,
        WW001_PA string,
        WW002_PA string,
        WW003_PA string,
        WW004_PA string,
        WW005_PA string,
        WW006_PA string,
        WW007_PA string,
        WW008_PA string,
        WW009_PA string,
        WW010_PA string,
        WW011_PA string,
        KVGR1_PA string,
        KVGR2_PA string,
        MVGR1_PA string,
        MVGR2_PA string,
        KVGR3_PA string,
        KTGRD_PA string,
        RE_BUKRS string,
        RE_ACCOUNT string,
        FIKRS string,
        FISTL string,
        MEASURE string,
        RFUND string,
        RGRANT_NBR string,
        RBUDGET_PD string,
        SFUND string,
        SGRANT_NBR string,
        SBUDGET_PD string,
        VNAME string,
        EGRUP string,
        RECID string,
        VPTNR string,
        BTYPE string,
        ETYPE string,
        PRODPER string,
        SWENR string,
        SGENR string,
        SGRNR string,
        SMENR string,
        RECNNR string,
        SNKSL string,
        SEMPSL string,
        DABRZ string,
        PSWENR string,
        PSGENR string,
        PSGRNR string,
        PSMENR string,
        PRECNNR string,
        PSNKSL string,
        PSEMPSL string,
        PDABRZ string,
        ACDOC_EEW_DUMMY string,
        DUMMY_INCL_EEW_COBL string,
        OIHANTYP string,
        OITAXGRP string,
        OIEXGNUM string,
        OIEXGTYP string,
        OITAXQT decimal(38,18),
        OIUOMQT string,
        OITAXVAL decimal(38,18),
        OIFULTAX decimal(38,18),
        OITXVAL0 decimal(38,18),
        OITXVAL1 decimal(38,18),
        OITXVAL2 decimal(38,18),
        OITXVAL3 decimal(38,18),
        OITXVAL4 decimal(38,18),
        OITXVAL5 decimal(38,18),
        OITXVAL6 decimal(38,18),
        FUP_ACTION string,
        MIG_SOURCE string,
        MIG_DOCLN string,
        _DATAAGING string,
        PREC_BUKRS string,
        PREC_GJAHR string,
        PREC_BELNR string,
        PREC_DOCLN string,
        CLOSING_RUN_ID binary,
        SRC_AWTYP string,
        SRC_AWSYS string,
        SRC_AWORG string,
        SRC_AWREF string,
        SRC_AWITEM string,
        SRC_AWSUBIT string,
        XCOMMITMENT string,
        OBS_REASON string,
        BSLALT decimal(38,18),
        CSLALT decimal(38,18),
        DSLALT decimal(38,18),
        ESLALT decimal(38,18),
        FSLALT decimal(38,18),
        GSLALT decimal(38,18),
        BSLEXT decimal(38,18),
        CSLEXT decimal(38,18),
        DSLEXT decimal(38,18),
        ESLEXT decimal(38,18),
        FSLEXT decimal(38,18),
        GSLEXT decimal(38,18),
        COCO_NUM string,
        WWERT string,
        INV_MOV_CATEG string,
        PS_PRJ_PNR string,
        SERVICE_DOC_TYPE string,
        SERVICE_DOC_ID string,
        SERVICE_DOC_ITEM_ID string,
        SERVICE_CONTRACT_TYPE string,
        SERVICE_CONTRACT_ID string,
        SERVICE_CONTRACT_ITEM_ID string,
        PPS_PSP_PNR string,
        PPS_PRJ_PNR string,
        PSERVICE_DOC_TYPE string,
        PSERVICE_DOC_ID string,
        PSERVICE_DOC_ITEM_ID string,
        OVERTIMECAT string,
        DUMMY_MRKT_SGMNT_EEW_PS string,
        BDGT_ACCOUNT string,
        BDGT_ACCOUNT_COCODE string,
        BDGT_CNSMPN_DATE string,
        BDGT_CNSMPN_PERIOD string,
        BDGT_CNSMPN_YEAR string,
        BDGT_RELEVANT string,
        BDGT_CNSMPN_TYPE string,
        BDGT_CNSMPN_AMOUNT_TYPE string,
        BILLM string,
        POM string,
        CBRUNID decimal(38,18),
        JVACTIVITY string,
        PVNAME string,
        PEGRUP string,
        S_RECIND string,
        CBRACCT string,
        CBOBJNR string,
        ACROBJTYPE string,
        ACROBJ_ID string,
        ACRSOBJ_ID string,
        ACRITMTYPE string,
        ACRVALDAT string,
        VALOBJTYPE string,
        VALOBJ_ID string,
        VALSOBJ_ID string,
        NETDT string,
        RISK_CLASS string,
        SDM_VERSION string,
        EBELN_LOGSYS string,
        VALUT string,
        ACRLOGSYS string,
        CBTTYPE string,
        CLOSINGSTEP string,
        AWITEM_REV string,
        ORGL_CHANGE string,
        RFCCUR string,
        RGM_OCUR string,
        RMSL_TYPE string,
        FCSL decimal(38,18),
        GM_OSL decimal(38,18),
        BUS_TRANS_ITEM_CATEGORY string,
        RBUNIT string,
        RBUPTR string,
        RCOMP string,
        RITCLG string,
        RITEM string,
        SITYP string,
        SUBIT string,
        PEROP_BEG string,
        PEROP_END string,
        PRCTR_DRVTN_SOURCE_TYPE string,
        TAX_COUNTRY string,
        AGING string,
        AGING_INCRMNT string,
        ANLN2_PN string,
        BWASL_PN string,
        BZDAT_PN string,
        ANBTR_PN decimal(38,18),
        PROF_SEG_TYPE string,
        UMATNR string,
        VARC_UACCT string,
        VARC_HKGRP string,
        SOLUTION_ORDER_ID string,
        SOLUTION_ORDER_ITEM_ID string,
        VTKEY string,
        VTPOS string,
        RA_CONTRACT_ID string,
        RA_POB_ID string,
        PAUFPS string,
        VORNR_ORG string,
        FIPEX string,
        RSPONSORED_PROG string,
        RSPONSORED_CLASS string,
        RBDGT_VLDTY_NBR string,
        KBLNR string,
        KBLPOS string,
        ACRREFOBJ_ID string,
        BRAN1_PA string,
        HIE01_PA string,
        HIE02_PA string,
        KUNRG_PA string,
        KVGR5_PA string,
        OIFPBL_PA string,
        OIFWE_PA string,
        PRODH_PA string,
        VKBUR_PA string,
        VKGRP_PA string,
        WW012_PA string,
        WW013_PA string,
        WW014_PA string,
        WW015_PA string,
        WW016_PA string,
        WW017_PA string,
        WW018_PA string,
        WW019_PA string,
        WW020_PA string,
        WW021_PA string,
        WW022_PA string,
        WW023_PA string,
        WW024_PA string,
        WW025_PA string,
        WW026_PA string,
        WW027_PA string,
        WW028_PA string,
        WW029_PA string,
        WW030_PA string,
        WW031_PA string,
        WW032_PA string,
        WW033_PA string,
        OIDRC_PA string,
        WW034_PA string,
        ZZ1_SENDERPARTY_JEI string,
        ZZ1_REFDOCNO_JEI string,
        ZZ1_BUSPROCID_JEI string,
        ZZ1_UNITOFMEASURE_JEI string,
        ZZ1_PRODUCT_JEI string,
        ZZ1_JNL_SDCO_CODE_JEI string,
        ZZ1_REFDOCYEAR_JEI string,
        ZZ1_QUANTITY_JEI string,
        ZZ1_REFDOCCOMPCODE_JEI string,
        ZZ1_ITEMQUANTITY_JEI decimal(38,18),
        -- metadata columns
        __etl_id BIGINT
            GENERATED ALWAYS AS IDENTITY,
        __etl_bronze_timestamp TIMESTAMP
            DEFAULT current_timestamp(),
        __etl_silver_timestamp TIMESTAMP,
        __etl_source_operation STRING
    )
    CLUSTER BY
        AUTO;
''')

# COMMAND ----------

# add the metadata columns back in
# spark.sql(f'''
#     ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.acdoca
#     ADD COLUMNS (
#         __etl_id BIGINT,
#         __etl_bronze_timestamp TIMESTAMP,
#         __etl_silver_timestamp TIMESTAMP,
#         __etl_source_operation STRING
#     );
# ''')


# COMMAND ----------

# NB: it takes about 25mins to copy the parquet file into the Delta table
# if we drop and recreate the Bronze table with the metadata columns (in dev and int)
# and we are doing it for Jan + Feb 2024, Sep 2024, Dec 2024, Jan + Feb 2025 = 6 months
# then it should take approx 2hrs to get Bronze sorted
#
# Then we need to rebuild Silver and Gold


# COMMAND ----------

# TODO: check with the FiveTran process what the naming convention will be? (uppercase, or lowercase column names?)
# Also, a bunch of the datatypes have changed.
