# Databricks notebook source
# MAGIC %run ../../../common/properties

# COMMAND ----------

dbutils.widgets.dropdown(
    name = 'table_operation',
    defaultValue = 'CREATE TABLE IF NOT EXISTS', 
    choices = [
        'CREATE TABLE IF NOT EXISTS',
        'CREATE OR REPLACE'
    ],
    label = '1- Table Operation'
)

table_operation = dbutils.widgets.get('table_operation')

# COMMAND ----------

table_name = 'acdocp'

# COMMAND ----------

spark,sql(f'''
    ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    SET TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'enabled');
''')

# COMMAND ----------

spark.sql(f'''
    -- CREATE TABLE IF NOT EXISTS
    {table_operation} {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    (
        RCLNT string,
        REQTSN string,
        DATAPAKID string,
        RECORD int,
        RYEAR string,
        RLDNR string,
        RACCT string,
        RBUKRS string,
        AWTYP string,
        USNAM string,
        CATEGORY string,
        KPRICE decimal(38,18),
        HPRICE decimal(38,18),
        WPRICE decimal(38,18),
        RMVCT string,
        BTTYPE string,
        AWORG string,
        AWREF string,
        RWCUR string,
        RHCUR string,
        RKCUR string,
        ROCUR string,
        RVCUR string,
        RBCUR string,
        RCCUR string,
        RDCUR string,
        RECUR string,
        RFCUR string,
        RGCUR string,
        RCO_OCUR string,
        RVUNIT string,
        RCNTR string,
        PRCTR string,
        RFAREA string,
        RBUSA string,
        KOKRS string,
        SEGMENT string,
        SCNTR string,
        PPRCTR string,
        SFAREA string,
        SBUSA string,
        RASSC string,
        PSEGMENT string,
        WSL decimal(38,18),
        HSL decimal(38,18),
        KSL decimal(38,18),
        OSL decimal(38,18),
        VSL decimal(38,18),
        BSL decimal(38,18),
        CSL decimal(38,18),
        DSL decimal(38,18),
        ESL decimal(38,18),
        FSL decimal(38,18),
        GSL decimal(38,18),
        VMSL decimal(38,18),
        KFSL decimal(38,18),
        CO_OSL decimal(38,18),
        POPER string,
        BUDAT string,
        PERIV string,
        FISCYEARPER string,
        KTOPL string,
        KDAUF string,
        KDPOS string,
        MATNR string,
        WERKS string,
        KUNNR string,
        SGTXT string,
        CO_BELKZ string,
        PS_PSP_PNR string,
        PS_POSID string,
        PS_PSPID string,
        PERNR string,
        PBUKRS string,
        ACCASTY string,
        LSTAR string,
        AUFNR string,
        RSRCE string,
        PAUFNR string,
        PACCASTY string,
        PLSTAR string,
        PPS_PSPID string,
        PPS_POSID string,
        WORK_ITEM_ID string,
        ACDOC_EEW_DUMMY string,
        DUMMY_INCL_EEW_COBL string,
        OIHANTYP string,
        OITAXGRP string,
        OIEXGNUM string,
        OIEXGTYP string,
        OITAXQT decimal(38,18),
        OIUOMQT string,
        OITAXVAL decimal(38,18),
        OIFULTAX decimal(38,18),
        OITXVAL0 decimal(38,18),
        OITXVAL1 decimal(38,18),
        OITXVAL2 decimal(38,18),
        OITXVAL3 decimal(38,18),
        OITXVAL4 decimal(38,18),
        OITXVAL5 decimal(38,18),
        OITXVAL6 decimal(38,18),
        FKART string,
        VKORG string,
        VTWEG string,
        SPART string,
        MATNR_COPA string,
        MATKL string,
        KDGRP string,
        LAND1 string,
        BRSCH string,
        BZIRK string,
        KUNRE string,
        KUNWE string,
        KONZS string,
        ACDOC_COPA_EEW_DUMMY_PA string,
        WW001_PA string,
        WW002_PA string,
        WW003_PA string,
        WW004_PA string,
        WW005_PA string,
        WW006_PA string,
        WW007_PA string,
        WW008_PA string,
        WW009_PA string,
        WW010_PA string,
        WW011_PA string,
        KVGR1_PA string,
        KVGR2_PA string,
        MVGR1_PA string,
        MVGR2_PA string,
        KVGR3_PA string,
        KTGRD_PA string,
        ARBID string,
        VORNR string,
        AUFPS string,
        PS_PRJ_PNR string,
        UPRCTR string,
        PPS_PSP_PNR string,
        PPS_PRJ_PNR string,
        BEMOT string,
        PSKNZ string,
        DUMMY_MRKT_SGMNT_EEW_PS string,
        FIKRS string,
        RFUND string,
        RGRANT_NBR string,
        RBUDGET_PD string,
        BUDGET_PROCESS string,
        BUDGET_SUBCATEGORY string,
        UVORN string,
        EQUNR string,
        TPLNR string,
        ISTRU string,
        ILART string,
        PLKNZ string,
        ARTPR string,
        PRIOK string,
        MAUFNR string,
        MATKL_MM string,
        RFCCUR string,
        RRUNIT string,
        FCSL decimal(38,18),
        WFSL decimal(38,18),
        HFSL decimal(38,18),
        VMFSL decimal(38,18),
        RMSL decimal(38,18),
        ZUONR string,
        SLALITTYPE string,
        NPLNR string,
        NPLNR_VORGN string,
        UKOSTL string,
        ULSTAR string,
        OBJNR string,
        AUFNR_ORG string,
        SERVICE_DOC_TYPE string,
        SERVICE_DOC_ID string,
        SERVICE_DOC_ITEM_ID string,
        SERVICE_CONTRACT_TYPE string,
        SERVICE_CONTRACT_ID string,
        SERVICE_CONTRACT_ITEM_ID string,
        GKONT string,
        GKOAR string,
        RSPONSORED_PROG string,
        RSPONSORED_CLASS string,
        RBDGT_VLDTY_NBR string,
        PAUFPS string,
        VORNR_ORG string,
        RSNUM string,
        RSPOS string,
        RSART string,
        PACKNO string,
        INTROW string,
        AFABE string,
        ANLN1 string,
        ANLN2 string,
        MOVCAT string,
        ANLKL string,
        VNAME string,
        EGRUP string,
        RECID string,
        PRODPER string,
        SWENR string,
        SGENR string,
        SGRNR string,
        SMENR string,
        RECNNR string,
        SNKSL string,
        SEMPSL string,
        DABRZ string,
        LSUNIT string,
        PMATNR string,
        COSTG_FROM_DATE string,
        COSTG_TO_DATE string,
        ASSL_SCRAP_INCLD string,
        ASSL_SCRAP_PCT decimal(38,18),
        SCRAP_FACTOR decimal(38,18),
        ASNUM string,
        INFNR string,
        LIFNR string,
        EKORG string,
        ESOKZ string,
        TYPPS string,
        STRAT string,
        HKGRP string,
        LOSGR decimal(38,18),
        SCRAP_QTY decimal(38,18),
        COMP_SCRAP_QTY decimal(38,18),
        ACROBJTYPE string,
        ACRLOGSYS string,
        ACROBJ_ID string,
        ACRSOBJ_ID string,
        ACRITMTYPE string,
        ACRREFOBJ_ID string,
        ACRVALDAT string,
        BRAN1_PA string,
        HIE01_PA string,
        HIE02_PA string,
        KUNRG_PA string,
        KVGR5_PA string,
        OIFPBL_PA string,
        OIFWE_PA string,
        PRODH_PA string,
        VKBUR_PA string,
        VKGRP_PA string,
        WW012_PA string,
        WW013_PA string,
        WW014_PA string,
        WW015_PA string,
        WW016_PA string,
        WW017_PA string,
        WW018_PA string,
        WW019_PA string,
        WW020_PA string,
        WW021_PA string,
        WW022_PA string,
        WW023_PA string,
        WW024_PA string,
        WW025_PA string,
        WW026_PA string,
        WW027_PA string,
        WW028_PA string,
        WW029_PA string,
        WW030_PA string,
        WW031_PA string,
        WW032_PA string,
        WW033_PA string,
        OIDRC_PA string,
        WW034_PA string,
        ZZ1_SENDERPARTY_JEI string,
        ZZ1_REFDOCNO_JEI string,
        ZZ1_BUSPROCID_JEI string,
        ZZ1_UNITOFMEASURE_JEI string,
        ZZ1_PRODUCT_JEI string,
        ZZ1_JNL_SDCO_CODE_JEI string,
        ZZ1_REFDOCYEAR_JEI string,
        ZZ1_QUANTITY_JEI string,
        ZZ1_REFDOCCOMPCODE_JEI string,
        ZZ1_ITEMQUANTITY_JEI decimal(38,18),

        -- metadata columns
        __etl_id BIGINT
            GENERATED ALWAYS AS IDENTITY,
        __etl_bronze_timestamp TIMESTAMP
            DEFAULT current_timestamp(),
        __etl_silver_timestamp TIMESTAMP,
        __etl_source_operation STRING
    )
    CLUSTER BY
        AUTO;
''')

# COMMAND ----------

# add the metadata columns back in
# spark.sql(f'''
#     ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.{table_name}
#     ADD COLUMNS (
#         __etl_id BIGINT,
#         __etl_bronze_timestamp TIMESTAMP,
#         __etl_silver_timestamp TIMESTAMP,
#         __etl_source_operation STRING
#     );
# ''')
