# Databricks notebook source
# MAGIC %run ../../../common/properties

# COMMAND ----------

dbutils.widgets.dropdown(
    name = 'table_operation',
    defaultValue = 'CREATE TABLE IF NOT EXISTS', 
    choices = [
        'CREATE TABLE IF NOT EXISTS',
        'CREATE OR REPLACE'
    ],
    label = '1- Table Operation'
)

table_operation = dbutils.widgets.get('table_operation')

# COMMAND ----------

table_name = 'kna1'

# COMMAND ----------

spark,sql(f'''
    ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    SET TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'enabled');
''')

# COMMAND ----------

spark.sql(f'''
    -- CREATE TABLE IF NOT EXISTS
    {table_operation} {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    (
        MANDT string,
        KUNNR string,
        LAND1 string,
        NAME1 string,
        NAME2 string,
        ORT01 string,
        PSTLZ string,
        REGIO string,
        SORTL string,
        STRAS string,
        TELF1 string,
        TELFX string,
        XCPDK string,
        ADRNR string,
        MCOD1 string,
        MCOD2 string,
        MCOD3 string,
        ANRED string,
        AUFSD string,
        BAHNE string,
        BAHNS string,
        BBBNR string,
        BBSNR string,
        BEGRU string,
        BRSCH string,
        BUBKZ string,
        DATLT string,
        ERDAT string,
        ERNAM string,
        EXABL string,
        FAKSD string,
        FISKN string,
        KNAZK string,
        KNRZA string,
        KONZS string,
        KTOKD string,
        KUKLA string,
        LIFNR string,
        LIFSD string,
        LOCCO string,
        LOEVM string,
        NAME3 string,
        NAME4 string,
        NIELS string,
        ORT02 string,
        PFACH string,
        PSTL2 string,
        COUNC string,
        CITYC string,
        RPMKR string,
        SPERR string,
        SPRAS string,
        STCD1 string,
        STCD2 string,
        STKZA string,
        STKZU string,
        TELBX string,
        TELF2 string,
        TELTX string,
        TELX1 string,
        LZONE string,
        XZEMP string,
        VBUND string,
        STCEG string,
        DEAR1 string,
        DEAR2 string,
        DEAR3 string,
        DEAR4 string,
        DEAR5 string,
        GFORM string,
        BRAN1 string,
        BRAN2 string,
        BRAN3 string,
        BRAN4 string,
        BRAN5 string,
        EKONT string,
        UMSAT decimal(38,18),
        UMJAH string,
        UWAER string,
        JMZAH string,
        JMJAH string,
        KATR1 string,
        KATR2 string,
        KATR3 string,
        KATR4 string,
        KATR5 string,
        KATR6 string,
        KATR7 string,
        KATR8 string,
        KATR9 string,
        KATR10 string,
        STKZN string,
        UMSA1 decimal(38,18),
        TXJCD string,
        PERIV string,
        ABRVW string,
        INSPBYDEBI string,
        INSPATDEBI string,
        KTOCD string,
        PFORT string,
        WERKS string,
        DTAMS string,
        DTAWS string,
        DUEFL string,
        HZUOR string,
        SPERZ string,
        ETIKG string,
        CIVVE string,
        MILVE string,
        KDKG1 string,
        KDKG2 string,
        KDKG3 string,
        KDKG4 string,
        KDKG5 string,
        XKNZA string,
        FITYP string,
        STCDT string,
        STCD3 string,
        STCD4 string,
        STCD5 string,
        XICMS string,
        XXIPI string,
        XSUBT string,
        CFOPC string,
        TXLW1 string,
        TXLW2 string,
        CCC01 string,
        CCC02 string,
        CCC03 string,
        CCC04 string,
        CASSD string,
        KNURL string,
        J_1KFREPRE string,
        J_1KFTBUS string,
        J_1KFTIND string,
        CONFS string,
        UPDAT string,
        UPTIM string,
        NODEL string,
        DEAR6 string,
        CVP_XBLCK string,
        SUFRAMA string,
        RG string,
        EXP string,
        UF string,
        RGDATE string,
        RIC string,
        RNE string,
        RNEDATE string,
        CNAE string,
        LEGALNAT string,
        CRTN string,
        ICMSTAXPAY string,
        INDTYP string,
        TDT string,
        COMSIZE string,
        DECREGPC string,
        KNA1_EEW_CUST string,
        `/ICO/LSPKZ` string,
        `/VSO/R_PALHGT` decimal(38,18),
        `/VSO/R_PAL_UL` string,
        `/VSO/R_PK_MAT` string,
        `/VSO/R_MATPAL` string,
        `/VSO/R_I_NO_LYR` string,
        `/VSO/R_ONE_MAT` string,
        `/VSO/R_ONE_SORT` string,
        `/VSO/R_ULD_SIDE` string,
        `/VSO/R_LOAD_PREF` string,
        `/VSO/R_DPOINT` string,
        ALC string,
        PMT_OFFICE string,
        FEE_SCHEDULE string,
        DUNS string,
        DUNS4 string,
        PSOFG string,
        PSOIS string,
        PSON1 string,
        PSON2 string,
        PSON3 string,
        PSOVN string,
        PSOTL string,
        PSOHS string,
        PSOST string,
        PSOO1 string,
        PSOO2 string,
        PSOO3 string,
        PSOO4 string,
        PSOO5 string,
        J_1IEXCD string,
        J_1IEXRN string,
        J_1IEXRG string,
        J_1IEXDI string,
        J_1IEXCO string,
        J_1ICSTNO string,
        J_1ILSTNO string,
        J_1IPANNO string,
        J_1IEXCICU string,
        AEDAT string,
        USNAM string,
        J_1ISERN string,
        J_1IPANREF string,
        J_3GETYP string,
        J_3GREFTYP string,
        PSPNR string,
        COAUFNR string,
        J_3GAGEXT string,
        J_3GAGINT string,
        J_3GAGDUMI string,
        J_3GAGSTDI string,
        LGORT string,
        KOKRS string,
        KOSTL string,
        J_3GABGLG string,
        J_3GABGVG string,
        J_3GABRART string,
        J_3GSTDMON decimal(38,18),
        J_3GSTDTAG decimal(38,18),
        J_3GTAGMON decimal(38,18),
        J_3GZUGTAG string,
        J_3GMASCHB string,
        J_3GMEINSA string,
        J_3GKEINSA string,
        J_3GBLSPER string,
        J_3GKLEIVO string,
        J_3GCALID string,
        J_3GVMONAT string,
        J_3GABRKEN string,
        J_3GLABRECH string,
        J_3GAABRECH string,
        J_3GZUTVHLG string,
        J_3GNEGMEN string,
        J_3GFRISTLO string,
        J_3GEMINBE string,
        J_3GFMGUE string,
        J_3GZUSCHUE string,
        J_3GSCHPRS string,
        J_3GINVSTA string,
        /SAPCEM/DBER string,
        /SAPCEM/KVMEQ string,
        OIDRC string,
        OID_POREQD string,
        OIPBL string,
        RES_CNTRY string,
        CCODE string,
        BONDED_AREA_CONFIRM string,
        DONATE_MARK string,
        RULE_EXCLUSION string,
        STCD6 string,
        CONSOLIDATE_INVOICE string,
        ALLOWANCE_TYPE string,
        EINVOICE_MODE string,
        B2C_INDICATOR string,
        DELIVERY_DATE_RULE string,
        PH_BIZ_STYLE string,
        PAYTRSN string,
        KNA1_ADDR_EEW_CUST string,
        SAM_UE_ID string,
        SAM_EFT_IND string,
        GST_TDS string,

        -- metadata columns
        __etl_id BIGINT
            GENERATED ALWAYS AS IDENTITY,
        __etl_bronze_timestamp TIMESTAMP
            DEFAULT current_timestamp(),
        __etl_silver_timestamp TIMESTAMP,
        __etl_source_operation STRING
    )
    CLUSTER BY
        AUTO;
''')

# COMMAND ----------

# add the metadata columns back in
# spark.sql(f'''
#     ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.{table_name}
#     ADD COLUMNS (
#         __etl_id BIGINT,
#         __etl_bronze_timestamp TIMESTAMP,
#         __etl_silver_timestamp TIMESTAMP,
#         __etl_source_operation STRING
#     );
# ''')
