# Databricks notebook source
# MAGIC %run ../../../common/properties

# COMMAND ----------

dbutils.widgets.dropdown(
    name = 'table_operation',
    defaultValue = 'CREATE TABLE IF NOT EXISTS', 
    choices = [
        'CREATE TABLE IF NOT EXISTS',
        'CREATE OR REPLACE'
    ],
    label = '1- Table Operation'
)

table_operation = dbutils.widgets.get('table_operation')

# COMMAND ----------

table_name = 'likp'

# COMMAND ----------

spark,sql(f'''
    ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    SET TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'enabled');
''')

# COMMAND ----------

spark.sql(f'''
    -- CREATE TABLE IF NOT EXISTS
    {table_operation} {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    (
        MANDT string,
        VBELN string,
        ERNAM string,
        ERZET string,
        ERDAT string,
        BZIRK string,
        VSTEL string,
        VKORG string,
        LFART string,
        AUTLF string,
        KZAZU string,
        WADAT string,
        LDDAT string,
        TDDAT string,
        LFDAT string,
        KODAT string,
        ABLAD string,
        INCO1 string,
        INCO2 string,
        EXPKZ string,
        ROUTE string,
        FAKSK string,
        LIFSK string,
        VBTYP string,
        KNFAK string,
        TPQUA string,
        TPGRP string,
        LPRIO string,
        VSBED string,
        KUNNR string,
        KUNAG string,
        KDGRP string,
        STZKL decimal(38,18),
        STZZU decimal(38,18),
        BTGEW decimal(38,18),
        NTGEW decimal(38,18),
        GEWEI string,
        VOLUM decimal(38,18),
        VOLEH string,
        ANZPK string,
        BEROT string,
        LFUHR string,
        GRULG string,
        LSTEL string,
        TRAGR string,
        FKARV string,
        FKDAT string,
        PERFK string,
        ROUTA string,
        STAFO string,
        KALSM string,
        KNUMV string,
        WAERK string,
        VKBUR string,
        VBEAK decimal(38,18),
        ZUKRL string,
        VERUR string,
        COMMN string,
        STWAE string,
        STCUR decimal(38,18),
        EXNUM string,
        AENAM string,
        AEDAT string,
        LGNUM string,
        LISPL string,
        VKOIV string,
        VTWIV string,
        SPAIV string,
        FKAIV string,
        PIOIV string,
        FKDIV string,
        KUNIV string,
        KKBER string,
        KNKLI string,
        GRUPP string,
        SBGRP string,
        CTLPC string,
        CMWAE string,
        AMTBL decimal(38,18),
        BOLNR string,
        LIFNR string,
        TRATY string,
        TRAID string,
        CMFRE string,
        CMNGV string,
        XABLN string,
        BLDAT string,
        WADAT_IST string,
        TRSPG string,
        TPSID string,
        LIFEX string,
        TERNR string,
        KALSM_CH string,
        KLIEF string,
        KALSP string,
        KNUMP string,
        NETWR decimal(38,18),
        AULWE string,
        WERKS string,
        LCNUM string,
        ABSSC string,
        KOUHR string,
        TDUHR string,
        LDUHR string,
        WAUHR string,
        LGTOR string,
        LGBZO string,
        AKWAE string,
        AKKUR decimal(38,18),
        AKPRZ decimal(38,18),
        PROLI string,
        XBLNR string,
        HANDLE string,
        TSEGFL string,
        TSEGTP string,
        TZONIS string,
        TZONRC string,
        CONT_DG string,
        VERURSYS string,
        KZWAB string,
        TCODE string,
        VSART string,
        TRMTYP string,
        SDABW string,
        VBUND string,
        XWOFF string,
        DIRTA string,
        PRVBE string,
        FOLAR string,
        PODAT string,
        POTIM string,
        VGANZ int,
        IMWRK string,
        SPE_LOEKZ string,
        SPE_LOC_SEQ string,
        SPE_ACC_APP_STS string,
        SPE_SHP_INF_STS string,
        SPE_RET_CANC string,
        SPE_WAUHR_IST string,
        SPE_WAZONE_IST string,
        SPE_REV_VLSTK string,
        SPE_LE_SCENARIO string,
        SPE_ORIG_SYS string,
        SPE_CHNG_SYS string,
        SPE_GEOROUTE string,
        SPE_GEOROUTEIND string,
        SPE_CARRIER_IND string,
        SPE_GTS_REL string,
        SPE_GTS_RT_CDE string,
        SPE_REL_TMSTMP decimal(38,18),
        SPE_UNIT_SYSTEM string,
        SPE_INV_BFR_GI string,
        SPE_QI_STATUS string,
        SPE_RED_IND string,
        SAKES string,
        SPE_LIFEX_TYPE string,
        SPE_TTYPE string,
        SPE_PRO_NUMBER string,
        LOC_GUID binary,
        SPE_BILLING_IND string,
        PRINTER_PROFILE string,
        MSR_ACTIVE string,
        PRTNR string,
        STGE_LOC_CHANGE string,
        TM_CTRL_KEY string,
        DLV_SPLIT_INITIA string,
        DLV_VERSION string,
        _DATAAGING string,
        GTS_VORPA string,
        GTS_VORNU string,
        GTS_EXPVZ string,
        GTS_PORTI string,
        ITM_EXPVZ string,
        ITM_STGBE string,
        ITM_KZGBE string,
        ITM_VYGID string,
        ITM_IEVER string,
        ITM_STABE string,
        ITM_KZABE string,
        HANDOVERLOC string,
        HANDOVERDATE string,
        HANDOVERTIME string,
        HANDOVERTZONE string,
        BESTK string,
        CMPSC string,
        CMPSD string,
        CMPSI string,
        CMPSJ string,
        CMPSK string,
        CMPS_CM string,
        CMPS_TE string,
        CMGST string,
        FKIVK string,
        FKSTK string,
        GBSTK string,
        HDALL string,
        HDALS string,
        KOQUK string,
        KOSTK string,
        LVSTK string,
        PDSTK string,
        PKSTK string,
        SPE_TMPID string,
        SPSTG string,
        TRSTA string,
        UVALL string,
        UVALS string,
        UVFAK string,
        UVFAS string,
        UVPAK string,
        UVPAS string,
        UVPIK string,
        UVPIS string,
        UVVLK string,
        UVVLS string,
        UVWAK string,
        UVWAS string,
        VESTK string,
        VLSTK string,
        WBSTK string,
        UVK01 string,
        UVK02 string,
        UVK03 string,
        UVK04 string,
        UVK05 string,
        UVS01 string,
        UVS02 string,
        UVS03 string,
        UVS04 string,
        UVS05 string,
        `/SAPMP/LBASK` string,
        OIG_SSTSF string,
        OIC_NXTINV string,
        INCOV string,
        INCO2_L string,
        INCO3_L string,
        OID_EXTBOL string,
        OID_MISCDL string,
        DUMMY_DELIVERY_INCL_EEW_PS string,
        `/BEV1/LULEINH` string,
        `/BEV1/RPFAESS` decimal(38,18),
        `/BEV1/RPKIST` decimal(38,18),
        `/BEV1/RPCONT` decimal(38,18),
        `/BEV1/RPSONST` decimal(38,18),
        `/BEV1/RPFLGNR` string,
        IDT_CUR_EVTLOC string,
        IDT_CUR_EVTQUA string,
        IDT_CUR_EVTTST decimal(38,18),
        IDT_CUR_ESTLOC string,
        IDT_CUR_ESTQUA string,
        IDT_CUR_ESTTST decimal(38,18),
        IDT_CUR_WRKQUA string,
        IDT_PRE_EVTLOC string,
        IDT_PRE_EVTQUA string,
        IDT_PRE_EVTTST decimal(38,18),
        IDT_PRE_ESTLOC string,
        IDT_PRE_ESTQUA string,
        IDT_PRE_ESTTST decimal(38,18),
        IDT_PRE_WRKQUA string,
        IDT_REF_ESTLOC string,
        IDT_REF_ESTQUA string,
        IDT_REF_ESTTST decimal(38,18),
        IDT_FIRM_LFDAT string,
        IDT_DOCNUM string,
        BORGR_GRP string,
        KBNKZ string,
        FSH_TRANSACTION string,
        FSH_VAS_LAST_ITEM string,
        FSH_VAS_CG string,
        RFM_PSST_GROUP string,
        OIC_TIME string,
        OIWATIM string,
        OILDTIM string,
        OIPIPEVAL string,
        OIC_LIFNR string,
        OIC_DCITYC string,
        OIC_DCOUNC string,
        OIC_DREGIO string,
        OIC_DLAND1 string,
        OIC_OCITYC string,
        OIC_OCOUNC string,
        OIC_OREGIO string,
        OIC_OLAND1 string,
        OIC_PORGIN string,
        OIC_PDESTN string,
        OIC_PTRIP string,
        OIC_PBATCH string,
        OIC_MOT string,
        OIC_AORGIN string,
        OIC_ADESTN string,
        OIC_TRUCKN string,
        OIA_BASELO string,
        OICFKARTDI string,
        OICSDP_DVERNO string,
        OIHNOTWERKS string,
        OIHCOTDISCH string,
        PODKZ string,
        OIO_HOLD string,
        OIO_HOLD_ORIG string,
        TOTAL_PCSTA string,
        TOTAL_DGSTA string,
        TOTAL_SDSSTA string,
        EXT_BUS_SYST_ID string,
        SITKZ_DB string,
        JIT_RLVNT string,
        KOSTK_WH string,
        TOTAL_ARC_STATUS string,
        ICO_FKIVK string,
        TOTAL_EMCST string,
        TOTAL_SLCST string,
        TOTAL_LCCST string,
        INCO2_KEY binary,
        INCO3_KEY binary,
        INCO4_KEY binary,
        TM_ADV_SHIP_RECV string,
        TM_WHSE_EXEC string,
        TM_WHSE_BLOCK string,
        LGLC_LIC_IND string,
        CREATION_TS decimal(38,18),
        CHANGED_TS decimal(38,18),
        CORR_IND string,
        EXT_ACT_DATE_TOCD decimal(38,18),
        EXT_PLAN_DATE_TOCD decimal(38,18),
        EXT_TZONE_TOCD string,
        INT_ACT_DATE_TOCD decimal(38,18),
        INT_PLAN_DATE_TOCD decimal(38,18),
        INT_TZONE_TOCD string,

        -- metadata columns
        __etl_id BIGINT
            GENERATED ALWAYS AS IDENTITY,
        __etl_bronze_timestamp TIMESTAMP
            DEFAULT current_timestamp(),
        __etl_silver_timestamp TIMESTAMP,
        __etl_source_operation STRING
    )
    CLUSTER BY
        AUTO;
''')

# COMMAND ----------

# add the metadata columns back in
# spark.sql(f'''
#     ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.{table_name}
#     ADD COLUMNS (
#         __etl_id BIGINT,
#         __etl_bronze_timestamp TIMESTAMP,
#         __etl_silver_timestamp TIMESTAMP,
#         __etl_source_operation STRING
#     );
# ''')
