# Databricks notebook source
# MAGIC %run ../../../common/properties

# COMMAND ----------

dbutils.widgets.dropdown(
    name = 'table_operation',
    defaultValue = 'CREATE TABLE IF NOT EXISTS', 
    choices = [
        'CREATE TABLE IF NOT EXISTS',
        'CREATE OR REPLACE'
    ],
    label = '1- Table Operation'
)

table_operation = dbutils.widgets.get('table_operation')

# COMMAND ----------

table_name = 'mara'

# COMMAND ----------

spark,sql(f'''
    ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    SET TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'enabled');
''')

# COMMAND ----------

spark.sql(f'''
    -- CREATE TABLE IF NOT EXISTS
    {table_operation} {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    (
        MANDT string,
        MATNR string,
        ERSDA string,
        ERNAM string,
        LAEDA string,
        AENAM string,
        VPSTA string,
        PSTAT string,
        LVORM string,
        MTART string,
        MBRSH string,
        MATKL string,
        BISMT string,
        MEINS string,
        BSTME string,
        ZEINR string,
        ZEIAR string,
        ZEIVR string,
        ZEIFO string,
        AESZN string,
        BLATT string,
        BLANZ string,
        FERTH string,
        FORMT string,
        GROES string,
        WRKST string,
        NORMT string,
        LABOR string,
        EKWSL string,
        BRGEW decimal(38,18),
        NTGEW decimal(38,18),
        GEWEI string,
        VOLUM decimal(38,18),
        VOLEH string,
        BEHVO string,
        RAUBE string,
        TEMPB string,
        DISST string,
        TRAGR string,
        STOFF string,
        SPART string,
        KUNNR string,
        EANNR string,
        WESCH decimal(38,18),
        BWVOR string,
        BWSCL string,
        SAISO string,
        ETIAR string,
        ETIFO string,
        ENTAR string,
        EAN11 string,
        NUMTP string,
        LAENG decimal(38,18),
        BREIT decimal(38,18),
        HOEHE decimal(38,18),
        MEABM string,
        PRDHA string,
        AEKLK string,
        CADKZ string,
        QMPUR string,
        ERGEW decimal(38,18),
        ERGEI string,
        ERVOL decimal(38,18),
        ERVOE string,
        GEWTO decimal(38,18),
        VOLTO decimal(38,18),
        VABME string,
        KZREV string,
        KZKFG string,
        XCHPF string,
        VHART string,
        FUELG decimal(38,18),
        STFAK int,
        MAGRV string,
        BEGRU string,
        DATAB string,
        LIQDT string,
        SAISJ string,
        PLGTP string,
        MLGUT string,
        EXTWG string,
        SATNR string,
        ATTYP string,
        KZKUP string,
        KZNFM string,
        PMATA string,
        MSTAE string,
        MSTAV string,
        MSTDE string,
        MSTDV string,
        TAKLV string,
        RBNRM string,
        MHDRZ decimal(38,18),
        MHDHB decimal(38,18),
        MHDLP decimal(38,18),
        INHME string,
        INHAL decimal(38,18),
        VPREH decimal(38,18),
        ETIAG string,
        INHBR decimal(38,18),
        CMETH string,
        CUOBF string,
        KZUMW string,
        KOSCH string,
        SPROF string,
        NRFHG string,
        MFRPN string,
        MFRNR string,
        BMATN string,
        MPROF string,
        KZWSM string,
        SAITY string,
        PROFL string,
        IHIVI string,
        ILOOS string,
        SERLV string,
        KZGVH string,
        XGCHP string,
        KZEFF string,
        COMPL string,
        IPRKZ string,
        RDMHD string,
        PRZUS string,
        MTPOS_MARA string,
        BFLME string,
        MATFI string,
        CMREL string,
        BBTYP string,
        SLED_BBD string,
        GTIN_VARIANT string,
        GENNR string,
        RMATP string,
        GDS_RELEVANT string,
        WEORA string,
        HUTYP_DFLT string,
        PILFERABLE string,
        WHSTC string,
        WHMATGR string,
        HNDLCODE string,
        HAZMAT string,
        HUTYP string,
        TARE_VAR string,
        MAXC decimal(38,18),
        MAXC_TOL decimal(38,18),
        MAXL decimal(38,18),
        MAXB decimal(38,18),
        MAXH decimal(38,18),
        MAXDIM_UOM string,
        HERKL string,
        MFRGR string,
        QQTIME decimal(38,18),
        QQTIMEUOM string,
        QGRP string,
        `SERIAL` string,
        PS_SMARTFORM string,
        LOGUNIT string,
        CWQREL string,
        CWQPROC string,
        CWQTOLGR string,
        ADPROF string,
        IPMIPPRODUCT string,
        ALLOW_PMAT_IGNO string,
        MEDIUM string,
        COMMODITY string,
        ANIMAL_ORIGIN string,
        TEXTILE_COMP_IND string,
        LAST_CHANGED_TIME string,
        SGT_CSGR string,
        SGT_COVSA string,
        SGT_STAT string,
        SGT_SCOPE string,
        SGT_REL string,
        ANP string,
        PSM_CODE string,
        FSH_MG_AT1 string,
        FSH_MG_AT2 string,
        FSH_MG_AT3 string,
        FSH_SEALV string,
        FSH_SEAIM string,
        FSH_SC_MID string,
        DUMMY_PRD_INCL_EEW_PS string,
        SCM_MATID_GUID16 binary,
        SCM_MATID_GUID22 string,
        SCM_MATURITY_DUR decimal(38,18),
        SCM_SHLF_LFE_REQ_MIN decimal(38,18),
        SCM_SHLF_LFE_REQ_MAX decimal(38,18),
        SCM_PUOM string,
        `/CWM/XCWMAT` string,
        `/CWM/VALUM` string,
        `/CWM/TOLGR` string,
        `/CWM/TARA` string,
        `/CWM/TARUM` string,
        `/BEV1/LULEINH` string,
        `/BEV1/LULDEGRP` string,
        `/BEV1/NESTRUCCAT` string,
        `/DSD/SL_TOLTYP` string,
        `/DSD/SV_CNT_GRP` string,
        `/DSD/VC_GROUP` string,
        `/SAPMP/KADU` decimal(38,18),
        `/SAPMP/ABMEIN` string,
        `/SAPMP/KADP` decimal(38,18),
        `/SAPMP/BRAD` decimal(38,18),
        `/SAPMP/SPBI` decimal(38,18),
        `/SAPMP/TRAD` decimal(38,18),
        `/SAPMP/KEDU` decimal(38,18),
        `/SAPMP/SPTR` decimal(38,18),
        `/SAPMP/FBDK` decimal(38,18),
        `/SAPMP/FBHK` decimal(38,18),
        `/SAPMP/RILI` string,
        `/SAPMP/FBAK` string,
        `/SAPMP/AHO` string,
        `/SAPMP/MIFRR` decimal(38,18),
        `/VSO/R_TILT_IND` string,
        `/VSO/R_STACK_IND` string,
        `/VSO/R_BOT_IND` string,
        `/VSO/R_TOP_IND` string,
        `/VSO/R_STACK_NO` string,
        `/VSO/R_PAL_IND` string,
        `/VSO/R_PAL_OVR_D` decimal(38,18),
        `/VSO/R_PAL_OVR_W` decimal(38,18),
        `/VSO/R_PAL_B_HT` decimal(38,18),
        `/VSO/R_PAL_MIN_H` decimal(38,18),
        `/VSO/R_TOL_B_HT` decimal(38,18),
        `/VSO/R_NO_P_GVH` string,
        `/VSO/R_QUAN_UNIT` string,
        `/VSO/R_KZGVH_IND` string,
        PACKCODE string,
        DG_PACK_STATUS string,
        MCOND string,
        RETDELC string,
        LOGLEV_RETO string,
        NSNID string,
        OVLPN string,
        ADSPC_SPC string,
        VARID binary,
        MSBOOKPARTNO string,
        DPCBT string,
        XGRDT string,
        IMATN string,
        PICNUM string,
        BSTAT string,
        COLOR_ATINN string,
        SIZE1_ATINN string,
        SIZE2_ATINN string,
        COLOR string,
        SIZE1 string,
        SIZE2 string,
        FREE_CHAR string,
        CARE_CODE string,
        BRAND_ID string,
        FIBER_CODE1 string,
        FIBER_PART1 string,
        FIBER_CODE2 string,
        FIBER_PART2 string,
        FIBER_CODE3 string,
        FIBER_PART3 string,
        FIBER_CODE4 string,
        FIBER_PART4 string,
        FIBER_CODE5 string,
        FIBER_PART5 string,
        FASHGRD string,
        OIGROUPNAM string,
        OITRIND string,
        OIHMTXGR string,
        CREATED_AT_TIME string,
        MATNR_EXTERNAL string,
        CHML_CMPLNC_RLVNCE_IND string,
        LOGISTICAL_MAT_CATEGORY string,
        SALES_MATERIAL string,
        IDENTIFICATION_TAG_TYPE string,
        RMATP_PB string,
        PROD_SHAPE string,
        MO_PROFILE_ID string,
        OVERHANG_TRESH decimal(38,18),
        BRIDGE_TRESH decimal(38,18),
        BRIDGE_MAX_SLOPE decimal(38,18),
        HEIGHT_NONFLAT decimal(38,18),
        HEIGHT_NONFLAT_UOM string,
        SCM_KITCOMP string,
        SCM_PROD_PAOOPT string,
        SCM_BOD_DEPLVL string,
        SCM_RESTRICT_INVBAL string,
        SCM_DRP_GL_STOCK string,
        SCM_EXCL_EXPEDITE string,
        `/STTPEC/SERTYPE` int,
        `/STTPEC/SYNCACT` string,
        `/STTPEC/SYNCTIME` decimal(38,18),
        `/STTPEC/SYNCCHG` string,
        `/STTPEC/COUNTRY_REF` string,
        `/STTPEC/PRDCAT` string,
        SRV_DURA decimal(38,18),
        SRV_DURA_UOM string,
        SRV_SERWI string,
        SRV_ESCAL string,
        SOM_CYCLE string,
        SOM_CYCLE_RULE string,
        SOM_TC_SCHEMA string,
        ICFA string,
        RIC_ID bigint,
        PRODUCTOID string,
        SDM_VERSION string,
        NEWPROD_INDI string,
        PRD_STARTDT string,
        PRD_ENDDT string,
        INV_PLN_MODE string,
        FLAGCLASS string,
        SOM_CTR_AUTORENEWAL string,
        DFS_SENSITIVITY_KEY string,
        DFS_MFRP2 string,
        TOLERANCE_TYPE string,

        -- metadata columns
        __etl_id BIGINT
            GENERATED ALWAYS AS IDENTITY,
        __etl_bronze_timestamp TIMESTAMP
            DEFAULT current_timestamp(),
        __etl_silver_timestamp TIMESTAMP,
        __etl_source_operation STRING
    )
    CLUSTER BY
        AUTO;
''')

# COMMAND ----------

# add the metadata columns back in
# spark.sql(f'''
#     ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.{table_name}
#     ADD COLUMNS (
#         __etl_id BIGINT,
#         __etl_bronze_timestamp TIMESTAMP,
#         __etl_silver_timestamp TIMESTAMP,
#         __etl_source_operation STRING
#     );
# ''')
