# Databricks notebook source
# MAGIC %run ../../../common/properties

# COMMAND ----------

dbutils.widgets.dropdown(
    name = 'table_operation',
    defaultValue = 'CREATE TABLE IF NOT EXISTS', 
    choices = [
        'CREATE TABLE IF NOT EXISTS',
        'CREATE OR REPLACE'
    ],
    label = '1- Table Operation'
)

table_operation = dbutils.widgets.get('table_operation')

# COMMAND ----------

table_name = 'vtbfhapo'

# COMMAND ----------

spark,sql(f'''
    ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    SET TBLPROPERTIES ('delta.feature.allowColumnDefaults' = 'enabled');
''')

# COMMAND ----------

spark.sql(f'''
    -- CREATE TABLE IF NOT EXISTS
    {table_operation} {env_vars.bronze_catalog}.sap_s4hana.{table_name}
    (
        MANDT string,
        BUKRS string,
        RFHA string,
        RFHAZU string,
        DCRDAT string,
        TCRTIM string,
        RFHAZB string,
        CRUSER string,
        UPUSER string,
        DUPDAT string,
        TUPTIM string,
        RANTYP string,
        SFHAZBA string,
        SBKKLAS string,
        SBKTYP string,
        SBERFIMA string,
        SSIGN string,
        SHERKUNFT string,
        SABVERF string,
        RKONDGR string,
        RKOND string,
        DGUEL_KP string,
        NSTUFE string,
        SKOART string,
        RREFKONT string,
        SBZVABW string,
        RAHABKI string,
        RAHKTID string,
        RPZAHL string,
        RPBANK string,
        SZART string,
        ZLSCH string,
        UZAWE string,
        SPAYRQ string,
        SPRSNG string,
        SPRGRD string,
        SCSPAY string,
        ZWELS string,
        PAYGR string,
        SBEWEBE string,
        SSPRGRD string,
        SBFREI string,
        SSTORNOBWG string,
        PRKEY string,
        BELNR string,
        BELNR2 string,
        GJAHR string,
        DBUCHUNG string,
        DFAELL string,
        DZTERM string,
        BZBETR decimal(38,18),
        WZBETR string,
        BHWBETR decimal(38,18),
        KHWKURS decimal(38,18),
        ASTUECK decimal(38,18),
        BPRICE decimal(38,18),
        WPRICE string,
        BHWPREIS decimal(38,18),
        BINDEX decimal(38,18),
        VVBASIS decimal(38,18),
        PWKURS decimal(38,18),
        PRKKURS decimal(38,18),
        BNWHR decimal(38,18),
        RHANDPL string,
        SKURSART string,
        DBERVON string,
        DBERBIS string,
        ATAGE string,
        ABASTAGE string,
        PKOND decimal(38,18),
        DPKOND string,
        DZFEST string,
        SZBMETH string,
        SKALIDWT string,
        BBASIS decimal(38,18),
        WBASIS string,
        JEXPOZINS string,
        SINCL string,
        SINCLBIS string,
        SULTBIS string,
        SEXCLVON string,
        SULTVON string,
        SAEND string,
        DVALUT string,
        SVINCL string,
        SVULT string,
        JSOFVERR string,
        DVERRECH string,
        SINCLVERR string,
        SULTVERR string,
        SSTORNOMAN string,
        SSTORNOART string,
        SBWGARTREF string,
        SKHWFIX string,
        ZUONR string,
        RLDEPO string,
        RANL string,
        RTRBELNR string,
        BUPRC decimal(38,18),
        BPPRC decimal(38,18),
        WBBETR string,
        BBBETR decimal(38,18),
        WEBETR string,
        BEBETR decimal(38,18),
        SRUNIT string,
        KZWKURS decimal(38,18),
        KBWKURS decimal(38,18),
        WSBETR string,
        DBESTAND string,
        SSTCKKZ string,
        SSTCKTG string,
        SFLAT string,
        SCOUPON string,
        DCOUPON string,
        AWKEY string,
        INDEX_VALUE decimal(38,18),
        SBASIS string,
        REGI_STATE string,
        RPCODE string,
        RP_TEXT string,
        HEDGE_ID string,
        DBPERIOD string,
        SPAEXCL string,
        SPAULT string,
        DEPERIOD string,
        SPEINCL string,
        SPEULT string,
        AMMRHY string,
        PPAYMENT decimal(38,18),
        AMMRHYZV string,
        LZBKZ string,
        LANDL string,
        BDIRTY decimal(38,18),
        BAMOUNTCOMP decimal(38,18),
        NOMINAL_ORG_AMT decimal(38,18),
        NOM_FACTOR decimal(38,18),
        RLDEPO2 string,
        INDEX_PRICE string,
        FLOWUUID binary,
        FLAGBYTE1 binary,
        QUANTITY decimal(38,18),
        UNIT_OF_MEASURE string,
        CONTRACT_PRICE decimal(38,18),
        SPOT_PRICE decimal(38,18),
        CONTANGO_BACKWRD decimal(38,18),
        BPRC_SPOT1 decimal(38,18),
        BPRC_SPOT2 decimal(38,18),
        COST_FWD decimal(38,18),
        INTEREST_FWD decimal(38,18),
        REF_FLOWUUID binary,
        RGATT string,
        COMMODITY_ID string,
        QUOTATION_NAME string,
        QUOTATION_SOURCE string,
        QUOTATION_TYPE string,
        SPREAD decimal(38,18),
        PRICE_CURR_UNIT string,
        PRICE_UOM string,
        DIV_PCTC_OTC decimal(38,18),
        TAINTED string,
        CLEARED string,
        DCSID string,
        MIC string,
        PRICE_TYPE string,
        TIME_TO_MATURITY string,
        TIMING string,
        EXCH_RATE_TYPE string,
        PRICE_PAYM_CURR decimal(38,18),
        SPREAD_PAYM_CURR decimal(38,18),
        FX_TRANSLATION string,
        MNDID string,
        BUGRENZ decimal(38,18),
        BOGRENZ decimal(38,18),
        SSTAFF string,
        LOGIC_RKOND string,
        RKONDREF string,
        DGUEL_KPREF string,
        PRESENT_DATE string,
        INTEREST_PAID_BY string,
        SHIPMENT_DATE string,
        STATUS string,
        PRESENT_ID string,
        SSTOGRD string,
        PRESENT_AMOUNT decimal(38,18),
        PRESENT_BANK string,
        PRESENT_DISCREPANCY string,
        PRESENT_DECREASE_AMOUNT decimal(38,18),
        PRESENT_REA_CRE_LINE decimal(38,18),
        PRESENT_PAY_AMT decimal(38,18),
        SKBWFIX string,
        IDCFM_USHA_TYPE string,
        IDCFM_USHA_PERC decimal(38,18),
        IDCFM_USHA_TOTA decimal(38,18),
        IDCFM_USHA_CURR string,
        IDCFM_USHA_FORM string,
        STGBASIS string,
        SROUNDFACTOR string,
        ROUNDDECFACTOR int,
        JEXPOINTFACTOR string,
        FLOWFACTOR binary,
        BASEFACTOR binary,
        SROUNDBASEFACTOR string,
        ROUNDDECBASEFACTOR int,
        GROUPING_TERM string,
        SSEQUENCE string,
        SROUNDRATEFACTOR string,
        ROUNDDECRATEFACTOR int,
        AAVGDAYS int,
        PAVGINTEREST decimal(38,18),
        JAVGCAP string,
        PAVGCAP decimal(38,18),
        JAVGFLOOR string,
        PAVGFLOOR decimal(38,18),
        PAVGSPREAD decimal(38,18),
        SROUNDAVGINTEREST string,
        ROUNDDECAVGINTEREST int,
        AAVGWEIGHT int,
        AAVGWEIGHTSUM int,
        FX_FIXING_DATE string,
        FX_REGI_STATE string,
        FX_READ_DATE string,
        PRICEINDEX_FIX_DATE_LOW string,
        PRICEINDEX_READ_DATE_LOW string,
        PRICEINDEX_FIX_DATE_HIGH string,
        PRICEINDEX_READ_DATE_HIGH string,
        PRICEINDEX_REGI_STATE string,
        BBBETR_IDXCLEAN decimal(38,18),
        TRADED_QUANTITY decimal(38,18),
        TRADED_QUANTITY_UOM string,
        CONV_FACTOR_TRADED_QTY decimal(38,18),
        CONV_FACTOR_TRADED_QTY_UOM string,
        CONV_FACTOR_PRICED_QTY decimal(38,18),
        CONV_FACTOR_PRICED_QTY_UOM string,
        BKOND decimal(38,18),
        IB_SCHEDULE_VERSION bigint,
        NOMINAL_VALUE_PER_UNIT string,
        SUM_RKOND string,
        SUM_ID_SOURCE string,
        SUM_ID_SUM string,

        -- metadata columns
        __etl_id BIGINT
            GENERATED ALWAYS AS IDENTITY,
        __etl_bronze_timestamp TIMESTAMP
            DEFAULT current_timestamp(),
        __etl_silver_timestamp TIMESTAMP,
        __etl_source_operation STRING
    )
    CLUSTER BY
        AUTO;
''')

# COMMAND ----------

# add the metadata columns back in
# spark.sql(f'''
#     ALTER TABLE {env_vars.bronze_catalog}.sap_s4hana.{table_name}
#     ADD COLUMNS (
#         __etl_id BIGINT,
#         __etl_bronze_timestamp TIMESTAMP,
#         __etl_silver_timestamp TIMESTAMP,
#         __etl_source_operation STRING
#     );
# ''')
